import { Header } from "@/components/Header";

export const metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default function GameLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
